# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('is_teacher', 'Is Teacher'), ('is_student', 'Is Student'))},
        ),
    ]
