# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 09:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20180926_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=1),
            preserve_default=False,
        ),
    ]
