# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_remove_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Product'),
        ),
    ]
