# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_auto_20181009_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': (('is_teacher', 'Is Teacher'), ('is_student', 'Is Student'))},
        ),
    ]
