# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20181009_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cuisines',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
    ]
