# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_auto_20181122_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cuisines',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=264),
        ),
    ]
